In [2]:
import pandas as pd
import geopandas as gpd
import numpy as np
from shapely.geometry import Point
from matplotlib import pyplot as plt
import matplotlib.gridspec as gridspec
from random import choice
pd.options.mode.chained_assignment = None 
import pickle

In [3]:
import os, sys
sys.path.append(os.path.join(os.path.expanduser('~'), 'Documents/Insert-Generic-Name-Here/'))
# sys.path

from lonelyboy.geospatial import plots as gsplt
from lonelyboy.geospatial import preprocessing as gspp
from lonelyboy.timeseries import lbtimeseries as tspp
# from lonelyboy.geospatial import group_patterns as gsgp


# from IPython.core.interactiveshell import InteractiveShell
# InteractiveShell.ast_node_interactivity = "all"
import PyQt5
import matplotlib.pyplot as plt
from matplotlib import style;  style.use('ggplot')
get_ipython().magic('matplotlib qt')
# get_ipython().magic('matplotlib inline')

In [4]:
ports = pd.read_pickle('./data/pkl/ports_raw.pkl')
traj  = pd.read_pickle('./data/pkl/subseted.pckl')

traj  = gspp.gdf_from_df(traj, crs={'init':'epsg:4326'})
traj.sort_values('ts', inplace=True)
ports = gspp.create_port_bounds(ports, epsg=2154, port_radius=2000)

In [5]:
gsplt.map_plot(traj, color=['steelblue'], title='Testing Trajectories', fontsize=10)

## Section 3: Distribution of AIS Activity

In [6]:
def segment_trajectories_v2(vessel, ports, port_radius=2000, port_epsg=2154):
    '''
    Segment trajectories based on port entrance/exit
    '''
    sindex = vessel.sindex # create the spatial index (r-tree) of the vessel's data points

    if (ports.geom.type == 'Point').all():
        ports = create_port_bounds(ports, port_radius=port_radius, epsg=port_epsg)

    # find the points that intersect with each subpolygon and add them to _points_within_geometry_ DataFrame
    points_within_geometry = pd.DataFrame()
    for poly in ports.geom:
        # find approximate matches with r-tree, then precise matches from those approximate ones
        possible_matches_index = list(sindex.intersection(poly.bounds))
        possible_matches = vessel.iloc[possible_matches_index]
        precise_matches = possible_matches[possible_matches.intersects(poly)]
        points_within_geometry = points_within_geometry.append(precise_matches)

    points_within_geometry = points_within_geometry.drop_duplicates(subset=['mmsi', 'ts'])
    points_outside_geometry = vessel[~vessel.isin(points_within_geometry)].dropna(how='all')

    vessel.loc[:,'traj_id'] = np.nan
    # When we create the _traj_id_ column, we label each record with 0, 
    # if it's outside the port's radius and -1 if it's inside the port's radius. 
    vessel.loc[vessel.index.isin(points_within_geometry.index), 'traj_id'] = -1
    vessel.loc[vessel.index.isin(points_outside_geometry.index), 'traj_id'] = 0
    
    # we drop the consecutive -1 rows, except the first and last one, and segment the trajectory by the remaining -1 points
    vessel = vessel.loc[vessel.traj_id[vessel.traj_id.replace(-1,np.nan).ffill(limit=1).bfill(limit=1).notnull()].index]
    vessel.reset_index(inplace=True, drop=True)

    dfs = np.split(vessel, vessel.loc[vessel.traj_id == -1].index)
    dfs = [df for df in dfs if len(df) > 0]    # remove the fragments that are empty
    # dfs = [df for df in dfs if len(df) >= 2]    # remove the fragments that have at most 1 point
    if (len(dfs) == 0):
#         print (vessel.columns)
#         return gpd.GeoDataFrame([], columns=['mmsi', 'speed', 'lon', 'lat', 'ts', 'geom', 'traj_id', 'traj_id_12h_gap'], geometry='geom', crs={'init':'epsg:4326'}) 
        return vessel.iloc[0:0]
    
    dfs[0].loc[:,'traj_id'] = 0    # ensure that the points in the first segments have the starting ID (0)    
    # then for each sub-trajectory, we assign an incrementing number (id) to each trajectory segment, starting from 0 
    for i in range(1,len(dfs)):
        if (len(dfs[i]) == 1):
            dfs[i].loc[:,'traj_id'] = dfs[i].traj_id.apply(lambda x: dfs[i-1].traj_id.max())
        else:
            dfs[i].loc[:,'traj_id'] = dfs[i].traj_id.apply(lambda x: x+dfs[i-1].traj_id.max()+1)				

    df_fn = pd.concat(dfs)
    df_fn.sort_values('ts', inplace=True)
    df_fn.reset_index(inplace=True, drop=True)
    return df_fn

In [7]:
def __temporal_segment(vessel, temporal_threshold=12):
    if len(vessel) == 0:
        vessel['traj_id_12h_gap'] = None
        return [vessel.iloc[0:0]]
#         return [gpd.GeoDataFrame([], columns=['mmsi', 'speed', 'lon', 'lat', 'ts', 'geom', 'traj_id', 'traj_id_12h_gap'], geometry='geom', crs={'init':'epsg:4326'})]
    
    print(f"Vessel: {vessel.mmsi.unique()[0]}")
    print(f"Segments Before: {len(vessel.traj_id.unique())}")
    vessel['traj_id_12h_gap'] = 0
    vessel.sort_values(['ts'], inplace=True)
    temporal_threshold = 12 # in hrs

    dfs_temporal = []

    for traj_id, sdf in vessel.groupby('traj_id'):
            df = sdf.reset_index()
            break_points = df.ts.diff(-1).abs().index[df.ts.diff()>60*60*temporal_threshold]

            if (len(break_points) > 0):
                    dfs = np.split(df, break_points)
            else:
                    dfs = [df]

            dfs_temporal.extend(dfs)
            #NOTE #1: Check np.split if break_points=[], returns traj

    dfs_temporal = [tmp_df for tmp_df in dfs_temporal if len(tmp_df) >= 2]
    print(f"Segments After: {len(dfs_temporal)}")

    if (len(dfs_temporal) == 0):
#         print (vessel.columns)
#         return [gpd.GeoDataFrame([], columns=['mmsi', 'speed', 'lon', 'lat', 'ts', 'geom', 'traj_id', 'traj_id_12h_gap'], geometry='geom', crs={'init':'epsg:4326'})]
        return [vessel.iloc[0:0]]
        
    dfs_temporal[0].loc[:,'traj_id_12h_gap'] = 0
    for idx in range(1, len(dfs_temporal)):
        dfs_temporal[idx].loc[:,'traj_id_12h_gap'] = dfs_temporal[idx].traj_id_12h_gap.apply(lambda x: x+dfs_temporal[idx-1].traj_id_12h_gap.max()+1)

    return dfs_temporal

In [8]:
def vessel_activity_outside_port(vessel, ports, port_epsg=2154, port_radius=2000, temporal_threshold=12):                                               
    port_bounds = gspp.create_port_bounds(ports, epsg=port_epsg, port_radius=port_radius)
    port_segmented_trajectories = segment_trajectories_v2(vessel, port_bounds)
    temporal_segmented_trajectories = __temporal_segment(port_segmented_trajectories, temporal_threshold=temporal_threshold)
    vessel_fn = pd.concat(temporal_segmented_trajectories, ignore_index=True)
    return vessel_fn

In [9]:
traj_seg = traj.groupby('mmsi', group_keys=False).apply(vessel_activity_outside_port, ports)
traj_seg.sort_values('ts', inplace=True)
traj_seg.reset_index(drop=True)

Vessel: 212228000
Segments Before: 1
Segments After: 0
Vessel: 212228000
Segments Before: 1
Segments After: 0
Vessel: 212228000
Segments Before: 1
Segments After: 0
Vessel: 212518000
Segments Before: 1
Segments After: 1
Vessel: 215477000
Segments Before: 2
Segments After: 2
Vessel: 218566000
Segments Before: 1
Segments After: 1
Vessel: 219118000
Segments Before: 1
Segments After: 1
Vessel: 220364000
Segments Before: 1
Segments After: 1
Vessel: 220417000
Segments Before: 2
Segments After: 2
Vessel: 220497000
Segments Before: 1
Segments After: 1
Vessel: 224130870
Segments Before: 1
Segments After: 2
Vessel: 226084000
Segments Before: 2
Segments After: 2
Vessel: 226177000
Segments Before: 1
Segments After: 0
Vessel: 226178000
Segments Before: 2
Segments After: 2
Vessel: 226179000
Segments Before: 2
Segments After: 2
Vessel: 226216000
Segments Before: 3
Segments After: 3
Vessel: 226263000
Segments Before: 6
Segments After: 6
Vessel: 226318000
Segments Before: 4
Segments After: 4
Vessel: 226338000
Segments Before: 3
Segments After: 3
Vessel: 227002630
Segments Before: 7
Segments After: 7
Vessel: 227003050
Segments Before: 12
Segments After: 12
Vessel: 227006750
Segments Before: 1
Segments After: 1
Vessel: 227113100
Segments Before: 2
Segments After: 2
Vessel: 227114300
Segments Before: 2
Segments After: 3
Vessel: 227143900
Segments Before: 1
Segments After: 1
Vessel: 227300000
Segments Before: 4
Segments After: 4
Vessel: 227303430
Segments Before: 2
Segments After: 2
Vessel: 227311000
Segments Before: 2
Segments After: 3
Vessel: 227312180
Segments Before: 1
Segments After: 1
Vessel: 227315110
Segments Before: 3
Segments After: 3
Vessel: 227318040
Segments Before: 1
Segments After: 1
Vessel: 227320660
Segments Before: 2
Segments After: 3
Vessel: 227322670
Segments Before: 6
Segments After: 6
Vessel: 227322690
Segments Before: 3
Segments After: 3
Vessel: 227327000
Segments Before: 1
Segments After: 0
Vessel: 227366000
Segments Before: 1
Segments After: 1
Vessel: 227392000
Segments Before: 4
Segments After: 4
Vessel: 227472000
Segments Before: 1
Segments After: 0
Vessel: 227567680
Segments Before: 1
Segments After: 0
Vessel: 227569380
Segments Before: 5
Segments After: 5
Vessel: 227574020
Segments Before: 14
Segments After: 14
Vessel: 227578460
Segments Before: 3
Segments After: 3
Vessel: 227588970
Segments Before: 3
Segments After: 3
Vessel: 227589520
Segments Before: 3
Segments After: 3
Vessel: 227590030
Segments Before: 6
Segments After: 6
Vessel: 227591030
Segments Before: 2
Segments After: 2
Vessel: 227592820
Segments Before: 14
Segments After: 14
Vessel: 227611930
Segments Before: 4
Segments After: 4
Vessel: 227612860
Segments Before: 4
Segments After: 4
Vessel: 227621940
Segments Before: 1
Segments After: 1
Vessel: 227631450
Segments Before: 6
Segments After: 6
Vessel: 227632830
Segments Before: 3
Segments After: 3
Vessel: 227635210
Segments Before: 10
Segments After: 10
Vessel: 227636480
Segments Before: 7
Segments After: 7
Vessel: 227639660
Segments Before: 3
Segments After: 3
Vessel: 227640190
Segments Before: 1
Segments After: 1
Vessel: 227640710
Segments Before: 5
Segments After: 5
Vessel: 227641920
Segments Before: 5
Segments After: 5
Vessel: 227650230
Segments Before: 3
Segments After: 3
Vessel: 227654220
Segments Before: 1
Segments After: 1
Vessel: 227666970
Segments Before: 2
Segments After: 2
Vessel: 227685830
Segments Before: 2
Segments After: 2
Vessel: 227686540
Segments Before: 3
Segments After: 3
Vessel: 227690560
Segments Before: 3
Segments After: 3
Vessel: 227705102
Segments Before: 13
Segments After: 13
Vessel: 227730220
Segments Before: 16
Segments After: 16
Vessel: 227762340
Segments Before: 10
Segments After: 10
Vessel: 227806500
Segments Before: 3
Segments After: 3
Vessel: 228005700
Segments Before: 9
Segments After: 9
Vessel: 228018800
Segments Before: 1
Segments After: 1
Vessel: 228021700
Segments Before: 1
Segments After: 1
Vessel: 228025700
Segments Before: 1
Segments After: 1
Vessel: 228070700
Segments Before: 1
Segments After: 1
Vessel: 228109000
Segments Before: 3
Segments After: 3
Vessel: 228126000
Segments Before: 1
Segments After: 1
Vessel: 228130000
Segments Before: 3
Segments After: 3
Vessel: 228144000
Segments Before: 2
Segments After: 2
Vessel: 228155700
Segments Before: 3
Segments After: 3
Vessel: 228167900
Segments Before: 2
Segments After: 2
Vessel: 228171600
Segments Before: 1
Segments After: 1
Vessel: 228174600
Segments Before: 1
Segments After: 1
Vessel: 228186700
Segments Before: 3
Segments After: 3
Vessel: 228190600
Segments Before: 3
Segments After: 3
Vessel: 228203800
Segments Before: 1
Segments After: 1
Vessel: 228210800
Segments Before: 1
Segments After: 1
Vessel: 228211900
Segments Before: 2
Segments After: 2
Vessel: 228219000
Segments Before: 1
Segments After: 1
Vessel: 228228800
Segments Before: 1
Segments After: 1
Vessel: 228236700
Segments Before: 2
Segments After: 2
Vessel: 228238700
Segments Before: 3
Segments After: 3
Vessel: 228258000
Segments Before: 1
Segments After: 2
Vessel: 228316000
Segments Before: 1
Segments After: 1
Vessel: 228336000
Segments Before: 2
Segments After: 2
Vessel: 228394000
Segments Before: 3
Segments After: 3
Vessel: 228762000
Segments Before: 22
Segments After: 22
Vessel: 228849000
Segments Before: 1
Segments After: 1
Vessel: 228853000
Segments Before: 1
Segments After: 1
Vessel: 228874000
Segments Before: 1
Segments After: 0
Vessel: 228893000
Segments Before: 1
Segments After: 1
Vessel: 228905000
Segments Before: 1
Segments After: 1
Vessel: 228917000
Segments Before: 1
Segments After: 0
Vessel: 228919000
Segments Before: 1
Segments After: 1
Vessel: 228922000
Segments Before: 1
Segments After: 1
Vessel: 228929000
Segments Before: 1
Segments After: 0
Vessel: 228935000
Segments Before: 1
Segments After: 0
Vessel: 228954000
Segments Before: 1
Segments After: 1
Vessel: 230631000
Segments Before: 1
Segments After: 0
Vessel: 232005610
Segments Before: 1
Segments After: 0
Vessel: 234056000
Segments Before: 10
Segments After: 10
Vessel: 235005980
Segments Before: 1
Segments After: 1
Vessel: 235058697
Segments Before: 1
Segments After: 1
Vessel: 235096859
Segments Before: 1
Segments After: 0
Vessel: 235098058
Segments Before: 1
Segments After: 1
Vessel: 235108972
Segments Before: 1
Segments After: 1
Vessel: 236471000
Segments Before: 1
Segments After: 0
Vessel: 244093000
Segments Before: 1
Segments After: 1
Vessel: 244227000
Segments Before: 1
Segments After: 1
Vessel: 244576000
Segments Before: 1
Segments After: 1
Vessel: 244674000
Segments Before: 1
Segments After: 1
Vessel: 244850852
Segments Before: 1
Segments After: 1
Vessel: 244925000
Segments Before: 4
Segments After: 4
Vessel: 244976000
Segments Before: 1
Segments After: 1
Vessel: 246051000
Segments Before: 1
Segments After: 0
Vessel: 247087700
Segments Before: 1
Segments After: 1
Vessel: 253380000
Segments Before: 1
Segments After: 0
Vessel: 255805250
Segments Before: 1
Segments After: 1
Vessel: 256494000
Segments Before: 2
Segments After: 2
Vessel: 258316000
Segments Before: 1
Segments After: 1
Vessel: 265425000
Segments Before: 1
Segments After: 1
Vessel: 273348830
Segments Before: 1
Segments After: 0
Vessel: 275457000
Segments Before: 1
Segments After: 1
Vessel: 304087000
Segments Before: 1
Segments After: 1
Vessel: 305476000
Segments Before: 1
Segments After: 1
Vessel: 311000094
Segments Before: 1
Segments After: 1
Vessel: 311000367
Segments Before: 1
Segments After: 0
Vessel: 311043200
Segments Before: 1
Segments After: 1
Vessel: 311051900
Segments Before: 1
Segments After: 1
Vessel: 311053100
Segments Before: 1
Segments After: 1
Vessel: 314207000
Segments Before: 1
Segments After: 1
Vessel: 357015000
Segments Before: 1
Segments After: 0
Vessel: 371415000
Segments Before: 1
Segments After: 1
Vessel: 477115900
Segments Before: 2
Segments After: 2
Vessel: 477220500
Segments Before: 1
Segments After: 1
Vessel: 477612300
Segments Before: 1
Segments After: 1
Vessel: 477986100
Segments Before: 1
Segments After: 1
Vessel: 538005628
Segments Before: 1
Segments After: 0
Vessel: 538090151
Segments Before: 1
Segments After: 1
Vessel: 563187000
Segments Before: 1
Segments After: 0
Vessel: 564224000
Segments Before: 1
Segments After: 1

Vessel: 566498000
Segments Before: 1
Segments After: 0
Vessel: 636009840
Segments Before: 1
Segments After: 1
Vessel: 636015106
Segments Before: 3
Segments After: 3
Vessel: 636016457
Segments Before: 2
Segments After: 2
Vessel: 636017106
Segments Before: 1
Segments After: 0
Vessel: 636017167
Segments Before: 1
Segments After: 1
Vessel: 636092271
Segments Before: 1
Segments After: 0
Vessel: 636092323
Segments Before: 1
Segments After: 0
Vessel: 636092331
Segments Before: 2
Segments After: 2

/home/andretri7/anaconda3/envs/gis/lib/python3.7/site-packages/pandas/core/groupby/groupby.py:927: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  result = concat(values, axis=self.axis)

,geom,index,lat,lon,mmsi,speed,traj_id,traj_id_12h_gap,ts
0,POINT (-4.631805 48.11133),0.0,48.111330,-4.631805,227300000,2.8,0.0,0,1456802713
1,POINT (-4.654577 48.12303499999999),0.0,48.123035,-4.654577,228394000,1.7,0.0,0,1456802716
2,POINT (-4.631777 48.11138),1.0,48.111380,-4.631777,227300000,2.7,0.0,0,1456802717
3,POINT (-4.631757 48.11142),2.0,48.111420,-4.631757,227300000,2.6,0.0,0,1456802720
4,POINT (-4.631747 48.111443),3.0,48.111443,-4.631747,227300000,2.5,0.0,0,1456802723
5,POINT (-4.631737999999999 48.111473),4.0,48.111473,-4.631738,227300000,2.3,0.0,0,1456802725
6,POINT (-4.6545033 48.12306),1.0,48.123060,-4.654503,228394000,1.8,0.0,0,1456802727
7,POINT (-4.6317234 48.111507),5.0,48.111507,-4.631723,227300000,2.2,0.0,0,1456802730
8,POINT (-4.63172 48.111526),6.0,48.111526,-4.631720,227300000,2.1,0.0,0,1456802732
9,POINT (-4.631708000000001 48.11157),7.0,48.111570,-4.631708,227300000,2.0,0.0,0,1456802737
10,POINT (-4.6544266 48.123074),2.0,48.123074,-4.654427,228394000,0.8,0.0,0,1456802737
11,POINT (-4.631703400000001 48.111588),8.0,48.111588,-4.631703,227300000,1.9,0.0,0,1456802740
12,POINT (-4.6316967 48.111614),9.0,48.111614,-4.631697,227300000,1.8,0.0,0,1456802743
13,POINT (-4.631688 48.11164),10.0,48.111640,-4.631688,227300000,1.8,0.0,0,1456802747
14,POINT (-4.654344999999999 48.123093),3.0,48.123093,-4.654345,228394000,1.5,0.0,0,1456802747
15,POINT (-4.631681400000001 48.11166),11.0,48.111660,-4.631681,227300000,1.6,0.0,0,1456802750
16,POINT (-4.631671400000001 48.11168),12.0,48.111680,-4.631671,227300000,1.6,0.0,0,1456802753
17,POINT (-4.631665 48.1117),13.0,48.111700,-4.631665,227300000,1.6,0.0,0,1456802756
18,POINT (-4.65428 48.12311),4.0,48.123110,-4.654280,228394000,1.1,0.0,0,1456802756
19,POINT (-4.63165 48.111725),14.0,48.111725,-4.631650,227300000,1.5,0.0,0,1456802759
20,POINT (-4.6316385 48.11174),15.0,48.111740,-4.631639,227300000,1.5,0.0,0,1456802763
21,POINT (-4.6316266 48.111763),16.0,48.111763,-4.631627,227300000,1.5,0.0,0,1456802767
22,POINT (-4.6542068 48.12314),5.0,48.123140,-4.654207,228394000,0.6,0.0,0,1456802767
23,POINT (-4.6316166 48.111774),17.0,48.111774,-4.631617,227300000,1.3,0.0,0,1456802770
24,POINT (-4.65413 48.12316),6.0,48.123160,-4.654130,228394000,0.7,0.0,0,1456802776
25,POINT (-4.631582 48.111813),18.0,48.111813,-4.631582,227300000,1.4,0.0,0,1456802777
26,POINT (-4.631561799999999 48.11183),19.0,48.111830,-4.631562,227300000,1.2,0.0,0,1456802782
27,POINT (-4.631545 48.111855),20.0,48.111855,-4.631545,227300000,1.1,0.0,0,1456802785
28,POINT (-4.654048400000001 48.123188),7.0,48.123188,-4.654048,228394000,0.8,0.0,0,1456802787
29,POINT (-4.631530000000001 48.111866),21.0,48.111866,-4.631530,227300000,1.2,0.0,0,1456802789
...,...,...,...,...,...,...,...,...,...
85255,POINT (-4.793245 48.135548),1910.0,48.135548,-4.793245,636092331,6.3,1.0,1,1456975214
85256,POINT (-4.79361 48.135803),1911.0,48.135803,-4.793610,636092331,6.7,1.0,1,1456975226
85257,POINT (-4.793925 48.135853),1912.0,48.135853,-4.793925,636092331,5.5,1.0,1,1456975235
85258,POINT (-4.794355 48.13611),1913.0,48.136110,-4.794355,636092331,6.2,1.0,1,1456975246
85259,POINT (-4.79462 48.136185),1914.0,48.136185,-4.794620,636092331,5.2,1.0,1,1456975256
85260,POINT (-4.7949514 48.13627),1915.0,48.136270,-4.794951,636092331,5.1,1.0,1,1456975265
85261,POINT (-4.7952566 48.136333),1916.0,48.136333,-4.795257,636092331,5.4,1.0,1,1456975274
85262,POINT (-4.7956614 48.13645),1917.0,48.136450,-4.795661,636092331,5.6,1.0,1,1456975286
85263,POINT (-4.79598 48.13652800000001),1918.0,48.136528,-4.795980,636092331,5.7,1.0,1,1456975295
85264,POINT (-4.79637 48.136585),1919.0,48.136585,-4.796370,636092331,5.2,1.0,1,1456975306
85265,POINT (-4.7966986 48.136703),1920.0,48.136703,-4.796699,636092331,5.4,1.0,1,1456975316
85266,POINT (-4.797043299999999 48.136875),1921.0,48.136875,-4.797043,636092331,6.2,1.0,1,1456975325
85267,POINT (-4.797332 48.137074),1922.0,48.137074,-4.797332,636092331,5.9,1.0,1,1456975334
85268,POINT (-4.79773 48.13730200000001),1923.0,48.137302,-4.797730,636092331,6.1,1.0,1,1456975346
85269,POINT (-4.798042 48.137432),1924.0,48.137432,-4.798042,636092331,6.3,1.0,1,1456975355
85270,POINT (-4.7984486 48.13764),1925.0,48.137640,-4.798449,636092331,6.0,1.0,1,1456975366
85271,POINT (-4.798769999999999 48.137726),1926.0,48.137726,-4.798770,636092331,5.6,1.0,1,1456975376
85272,POINT (-4.799144999999999 48.137886),1927.0,48.137886,-4.799145,636092331,6.1,1.0,1,1456975385
85273,POINT (-4.7994466 48.13800999999999),1928.0,48.138010,-4.799447,636092331,6.1,1.0,1,1456975395
85274,POINT (-4.7998233 48.13816),1929.0,48.138160,-4.799823,636092331,5.6,1.0,1,1456975406
85275,POINT (-4.800202 48.138332),1930.0,48.138332,-4.800202,636092331,6.5,1.0,1,1456975415
85276,POINT (-4.8005834 48.13852),1931.0,48.138520,-4.800583,636092331,6.3,1.0,1,1456975426
85277,POINT (-4.8009315 48.138695),1932.0,48.138695,-4.800931,636092331,6.3,1.0,1,1456975436
85278,POINT (-4.801262 48.138847),1933.0,48.138847,-4.801262,636092331,6.5,1.0,1,1456975445
85279,POINT (-4.801578500000001 48.139008),1934.0,48.139008,-4.801579,636092331,6.4,1.0,1,1456975455
85280,POINT (-4.8019834 48.13919),1935.0,48.139190,-4.801983,636092331,6.3,1.0,1,1456975465
85281,POINT (-4.8023515 48.139374),1936.0,48.139374,-4.802352,636092331,6.4,1.0,1,1456975475
85282,POINT (-4.802767 48.13956),1937.0,48.139560,-4.802767,636092331,6.2,1.0,1,1456975487
85283,POINT (-4.803088 48.13973),1938.0,48.139730,-4.803088,636092331,6.5,1.0,1,1456975497
85284,POINT (-4.803405000000001 48.139896),1939.0,48.139896,-4.803405,636092331,6.4,1.0,1,1456975506

In [10]:
traj_seg.head(20)

,geom,index,lat,lon,mmsi,speed,traj_id,traj_id_12h_gap,ts
0,POINT (-4.631805 48.11133),0.0,48.111330,-4.631805,227300000,2.8,0.0,0,1456802713
0,POINT (-4.654577 48.12303499999999),0.0,48.123035,-4.654577,228394000,1.7,0.0,0,1456802716
1,POINT (-4.631777 48.11138),1.0,48.111380,-4.631777,227300000,2.7,0.0,0,1456802717
2,POINT (-4.631757 48.11142),2.0,48.111420,-4.631757,227300000,2.6,0.0,0,1456802720
3,POINT (-4.631747 48.111443),3.0,48.111443,-4.631747,227300000,2.5,0.0,0,1456802723
4,POINT (-4.631737999999999 48.111473),4.0,48.111473,-4.631738,227300000,2.3,0.0,0,1456802725
1,POINT (-4.6545033 48.12306),1.0,48.123060,-4.654503,228394000,1.8,0.0,0,1456802727
5,POINT (-4.6317234 48.111507),5.0,48.111507,-4.631723,227300000,2.2,0.0,0,1456802730
6,POINT (-4.63172 48.111526),6.0,48.111526,-4.631720,227300000,2.1,0.0,0,1456802732
7,POINT (-4.631708000000001 48.11157),7.0,48.111570,-4.631708,227300000,2.0,0.0,0,1456802737
2,POINT (-4.6544266 48.123074),2.0,48.123074,-4.654427,228394000,0.8,0.0,0,1456802737
8,POINT (-4.631703400000001 48.111588),8.0,48.111588,-4.631703,227300000,1.9,0.0,0,1456802740
9,POINT (-4.6316967 48.111614),9.0,48.111614,-4.631697,227300000,1.8,0.0,0,1456802743
10,POINT (-4.631688 48.11164),10.0,48.111640,-4.631688,227300000,1.8,0.0,0,1456802747
3,POINT (-4.654344999999999 48.123093),3.0,48.123093,-4.654345,228394000,1.5,0.0,0,1456802747
11,POINT (-4.631681400000001 48.11166),11.0,48.111660,-4.631681,227300000,1.6,0.0,0,1456802750
12,POINT (-4.631671400000001 48.11168),12.0,48.111680,-4.631671,227300000,1.6,0.0,0,1456802753
13,POINT (-4.631665 48.1117),13.0,48.111700,-4.631665,227300000,1.6,0.0,0,1456802756
4,POINT (-4.65428 48.12311),4.0,48.123110,-4.654280,228394000,1.1,0.0,0,1456802756
14,POINT (-4.63165 48.111725),14.0,48.111725,-4.631650,227300000,1.5,0.0,0,1456802759

In [115]:
traj_seg.head(20)

,geom,index,lat,lon,mmsi,speed,traj_id,traj_id_12h_gap,ts
0,POINT (-4.631805 48.11133),0.0,48.111330,-4.631805,227300000,2.8,0.0,0,1456802713
0,POINT (-4.654577 48.12303499999999),0.0,48.123035,-4.654577,228394000,1.7,0.0,0,1456802716
1,POINT (-4.631777 48.11138),1.0,48.111380,-4.631777,227300000,2.7,0.0,0,1456802717
2,POINT (-4.631757 48.11142),2.0,48.111420,-4.631757,227300000,2.6,0.0,0,1456802720
3,POINT (-4.631747 48.111443),3.0,48.111443,-4.631747,227300000,2.5,0.0,0,1456802723
4,POINT (-4.631737999999999 48.111473),4.0,48.111473,-4.631738,227300000,2.3,0.0,0,1456802725
1,POINT (-4.6545033 48.12306),1.0,48.123060,-4.654503,228394000,1.8,0.0,0,1456802727
5,POINT (-4.6317234 48.111507),5.0,48.111507,-4.631723,227300000,2.2,0.0,0,1456802730
6,POINT (-4.63172 48.111526),6.0,48.111526,-4.631720,227300000,2.1,0.0,0,1456802732
7,POINT (-4.631708000000001 48.11157),7.0,48.111570,-4.631708,227300000,2.0,0.0,0,1456802737
2,POINT (-4.6544266 48.123074),2.0,48.123074,-4.654427,228394000,0.8,0.0,0,1456802737
8,POINT (-4.631703400000001 48.111588),8.0,48.111588,-4.631703,227300000,1.9,0.0,0,1456802740
9,POINT (-4.6316967 48.111614),9.0,48.111614,-4.631697,227300000,1.8,0.0,0,1456802743
10,POINT (-4.631688 48.11164),10.0,48.111640,-4.631688,227300000,1.8,0.0,0,1456802747
3,POINT (-4.654344999999999 48.123093),3.0,48.123093,-4.654345,228394000,1.5,0.0,0,1456802747
11,POINT (-4.631681400000001 48.11166),11.0,48.111660,-4.631681,227300000,1.6,0.0,0,1456802750
12,POINT (-4.631671400000001 48.11168),12.0,48.111680,-4.631671,227300000,1.6,0.0,0,1456802753
13,POINT (-4.631665 48.1117),13.0,48.111700,-4.631665,227300000,1.6,0.0,0,1456802756
4,POINT (-4.65428 48.12311),4.0,48.123110,-4.654280,228394000,1.1,0.0,0,1456802756
14,POINT (-4.63165 48.111725),14.0,48.111725,-4.631650,227300000,1.5,0.0,0,1456802759

In [116]:
traj_seg.reset_index(inplace=True, drop=True)

In [11]:
gsplt.map_plot(traj_seg, color=[None], column='traj_id', cmap='tab20',  title='Testing Trajectories Segments', fontsize=10, legend=True)

In [98]:
ais_activity_outside_port = traj_seg.groupby(['mmsi', 'traj_id_12h_gap', pd.to_datetime(traj_seg.ts, unit='s').dt.date], group_keys=False).apply(lambda df: df.ts.diff().sum()/3600).to_frame().reset_index()
ais_activity_outside_port.columns = ['mmsi', 'traj_id_temporal_gap','date', '#hrs']
ais_activity_outside_port

          mmsi  traj_id_temporal_gap        date       #hrs
0    205067000                     0  2015-10-22   1.843333
1    205067000                     0  2015-10-23  21.251389
2    205067000                     1  2016-02-10   1.249444
3    227519920                     0  2015-10-01   0.573889
4    227519920                     1  2015-10-01   0.400000
5    227519920                     2  2015-10-01   2.275000
6    227519920                     3  2015-10-01   0.350000
7    227519920                     4  2015-10-01   0.258889
8    227519920                     5  2015-10-01   0.117500
9    227519920                     6  2015-10-01   0.183611
10   227519920                     7  2015-10-03   0.791667
11   227519920                     8  2015-10-03   0.916389
12   227519920                     9  2015-10-03   0.449722
13   227519920                    10  2015-10-09   0.158056
14   227519920                    11  2015-10-10   0.600833
15   227519920                    12  2015-10-11   0.275000
16   227519920                    13  2015-10-18   0.691944
17   227519920                    14  2015-10-18   0.674722
18   227519920                    15  2015-10-18   2.516667
19   227519920                    16  2015-10-19   0.908056
20   227519920                    17  2015-10-19   1.058056
21   227519920                    18  2015-10-19   0.184167
22   227519920                    19  2015-10-24   0.358056
23   227519920                    20  2015-10-24   0.492222
24   227519920                    21  2015-10-24   1.183333
25   227519920                    22  2015-10-24   0.133333
26   227519920                    23  2015-10-29   0.549722
27   227519920                    24  2015-10-29   0.575278
28   227519920                    25  2015-10-30   0.399722
29   227519920                    26  2015-10-30   0.450278
..         ...                   ...         ...        ...
186  228037600                   121  2016-03-06   5.066667
187  228037600                   122  2016-03-06   1.819444
188  228037600                   122  2016-03-07   0.016667
189  228037600                   123  2016-03-07   6.377778
190  228037600                   124  2016-03-08   4.133611
191  228037600                   125  2016-03-08   0.994167
192  228037600                   126  2016-03-10   7.474722
193  228037600                   127  2016-03-13   1.805556
194  228037600                   128  2016-03-14   7.622500
195  228037600                   128  2016-03-15   0.302778
196  228037600                   129  2016-03-15   6.719444
197  228037600                   129  2016-03-16   0.061111
198  228037600                   130  2016-03-16   2.224722
199  228037600                   131  2016-03-17   6.180556
200  228037600                   132  2016-03-20   2.511389
201  228037600                   133  2016-03-21   5.400000
202  228037600                   134  2016-03-22   4.769167
203  228037600                   135  2016-03-23   5.744444
204  228037600                   135  2016-03-24   0.444444
205  228037600                   136  2016-03-29   3.747778
206  228037600                   137  2016-03-30   7.400000
207  228037600                   137  2016-03-31   0.375000
208  228037600                   138  2016-03-31   2.861111
209  228037600                   139  2016-03-31   1.188333
210  305166000                     0  2015-11-08   6.827778
211  305166000                     1  2015-11-08   0.124722
212  305166000                     2  2015-11-09   0.441944
213  305166000                     3  2015-11-09   0.825000
214  305166000                     3  2015-11-10   4.483333
215  305166000                     4  2015-11-13   3.508333

[216 rows x 4 columns]

In [23]:
tmp = points_within_geometry.groupby(['mmsi', pd.to_datetime(points_within_geometry.ts, unit='s').dt.date], group_keys=False).apply(lambda df: df.ts.diff().sum()/3600).to_frame().reset_index()
tmp.columns = ['mmsi', 'date', '#hrs']
tmp

          mmsi        date       #hrs
0    227519920  2015-10-01   5.449722
1    227519920  2015-10-02   0.016389
2    227519920  2015-10-03  12.791111
3    227519920  2015-10-04  11.842778
4    227519920  2015-10-06   4.775556
5    227519920  2015-10-08   1.158333
6    227519920  2015-10-09   2.733889
7    227519920  2015-10-10   2.858056
8    227519920  2015-10-11   1.857500
9    227519920  2015-10-12   0.558611
10   227519920  2015-10-15   1.900278
11   227519920  2015-10-17   3.241667
12   227519920  2015-10-18   6.591667
13   227519920  2015-10-19   0.233611
14   227519920  2015-10-20   1.369722
15   227519920  2015-10-21   1.259444
16   227519920  2015-10-24   4.450278
17   227519920  2015-10-25   2.199722
18   227519920  2015-10-26   0.374722
19   227519920  2015-10-29   2.761944
20   227519920  2015-10-30   4.483056
21   227519920  2015-11-02   2.966667
22   227519920  2015-11-03   0.250278
23   227519920  2015-11-04   2.840556
24   227519920  2015-11-05   0.000000
25   227519920  2015-11-06   2.174722
26   227519920  2015-11-07   4.010000
27   227519920  2015-11-08   3.123611
28   227519920  2015-11-09   6.400278
29   227519920  2015-11-11   4.208333
..         ...         ...        ...
117  228037600  2016-02-18   0.641944
118  228037600  2016-02-19   0.124722
119  228037600  2016-02-21   7.197222
120  228037600  2016-02-22   8.099722
121  228037600  2016-02-23  22.431667
122  228037600  2016-02-24   2.655556
123  228037600  2016-02-25   6.519444
124  228037600  2016-02-28   5.352778
125  228037600  2016-02-29   7.397222
126  228037600  2016-03-03   2.411389
127  228037600  2016-03-06   0.441944
128  228037600  2016-03-07  23.790278
129  228037600  2016-03-08   6.042222
130  228037600  2016-03-10   0.441667
131  228037600  2016-03-11   0.247222
132  228037600  2016-03-13   2.647222
133  228037600  2016-03-14   0.414167
134  228037600  2016-03-15  16.676667
135  228037600  2016-03-16  20.837778
136  228037600  2016-03-17   7.250000
137  228037600  2016-03-20   3.800278
138  228037600  2016-03-21   6.644722
139  228037600  2016-03-22   5.333333
140  228037600  2016-03-23   0.177500
141  228037600  2016-03-24   0.252778
142  228037600  2016-03-29   5.833611
143  228037600  2016-03-30   1.155556
144  228037600  2016-03-31  17.250000
145  305166000  2015-11-08  10.134167
146  305166000  2015-11-09   0.333611

[147 rows x 3 columns]

In [13]:
gsplt.map_plot(points_within_geometry, points_outside_geometry, color=['r','steelblue'], title='Points Outside/Inside Port Radius', fontsize=10)