In [1]:
import os, sys
sys.path.append(os.path.join(os.path.expanduser('~'), 'Code'))
# sys.path

from lonelyboy.geospatial import plots as gsplt
from lonelyboy.geospatial import preprocessing as gspp
from lonelyboy.timeseries import lbtimeseries as tspp
from lonelyboy.geospatial import group_patterns as gsgp
from lonelyboy.geospatial import moving_patterns as gsmp

## Importing all other Essential Libraries
#### (DO NOT FORGET TO EXECUTE THE FUNCTIONS IN THE BOTTOM CELLS)

import psycopg2
import numpy as np
import configparser
import pandas as pd
import geopandas as gpd
import contextily as ctx
from random import choice
from tqdm import tqdm
import matplotlib.pyplot as plt
from sklearn.base import clone
from sklearn.cluster import DBSCAN, KMeans, MeanShift
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import silhouette_score
from shapely.geometry import Point, LineString, shape
from haversine import haversine
from datetime import datetime, timedelta

from multiprocessing import cpu_count, Pool
from functools import partial
import datetime
import pandas as pd                                                                                                                                                                                            
import numpy as np
import networkx as nx
from scipy.spatial import distance_matrix

/home/theo/anaconda3/envs/gsa/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/theo/anaconda3/envs/gsa/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/theo/anaconda3/envs/gsa/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

In [2]:
import PyQt5
import matplotlib.pyplot as plt
from matplotlib import style;  style.use('ggplot')
get_ipython().magic('matplotlib qt')

In [3]:
def index_of_cluster(item, cluster_list):
    position = [ind for ind, subl in enumerate(cluster_list) if item in subl]
    if len(position)>1:
        raise ValueError
    if not position:
        return [-1]
    else:
        return position


def connected_edges(data):
    G = nx.Graph()
    G.add_edges_from(data)
    return [list(cluster) for cluster in nx.connected_components(G)]


def pairs_in_radius(df, radius):
    distances = np.triu(distance_matrix(df[['lat', 'lon']].values, df[['lat', 'lon']].values),0)
    distances[distances == 0] = np.inf
    return np.vstack(np.where(distances<=radius)).T


def get_flock_labels(timeframe,radius):
    timeframe.reset_index(drop=True , inplace=True)
    data = pairs_in_radius(timeframe, radius)
    clusters = connected_edges(data)
    timeframe['flock_label'] = timeframe.apply( lambda x: index_of_cluster(x.name, clusters)[0], axis=1)
    return timeframe


def flocks(df,radius):
    df['flock_label'] = np.nan
    df =  df.groupby('datetime', as_index=False).apply(get_flock_labels, radius)
    return df

In [4]:
def point_from_lat_lon(df_w_lat_lon):
    df_w_lat_lon['geom'] = np.nan
    df_w_lat_lon['geom'] = df_w_lat_lon[['lon', 'lat']].apply(lambda x: Point(x), axis=1)
    return gpd.GeoDataFrame(df_w_lat_lon, geometry='geom')

In [109]:
def get_correct_label(present, future):
#     cluster = present.loc[present.flock_label==label]
    lst = future.loc[future.mmsi.isin(present.mmsi)].flock_label.value_counts().index
    if lst[0] != -1 or len(lst)==1:
        return lst[0]
    else:
        return lst[1]
#         if new_label != label:
#             cmdlst.append((label, new_label))
#             tmp1 = present.flock_label
#             present['flock_label'] = present.flock_label.apply(lambda x: new_label if x==label else label if x==new_label else x)
#             tmp2 = present.flock_label
#     return cmdlst, tmp1, tmp2

In [6]:
def swap(x, pair):
    return pair[pair.index(x)-1] if x in pair else x

In [7]:
sample_timeFrame = pd.read_csv('4h_timeFrame_not_at_3_fing_am.csv')

In [8]:
sample_timeFrame = point_from_lat_lon(sample_timeFrame)

In [9]:
sample_timeFrame.head()

,id,mmsi,status,turn,speed,course,heading,lon,lat,ts,geom,velocity,datetime
0,1.884809e+07,227408710.0,0.0,0.0,0.000000,258.100000,511.000000,-4.490398,48.379186,1.456818e+09,POINT (-4.4903984 48.3791865),0.013741,2016-03-01 07:36:00
1,1.758572e+07,228853000.0,7.0,-127.0,6.169685,200.775984,511.000000,-3.891684,47.732670,1.456818e+09,POINT (-3.891684385826772 47.73266998031496),0.153449,2016-03-01 07:36:00
2,1.884808e+07,227686540.0,0.0,0.0,6.400000,199.300000,511.000000,-4.464395,48.327780,1.456818e+09,POINT (-4.464395 48.32778),6.911790,2016-03-01 07:36:00
3,1.751793e+07,226216000.0,7.0,0.0,0.000000,196.639167,302.466667,-4.175265,47.835712,1.456818e+09,POINT (-4.175265398333333 47.83571188333333),0.001396,2016-03-01 07:36:00
4,1.751790e+07,227270000.0,5.0,-127.0,0.000000,0.000000,511.000000,-4.478274,48.383153,1.456818e+09,POINT (-4.478274466666667 48.38315333333333),0.003177,2016-03-01 07:36:00

In [10]:
flocks_cluster = flocks(sample_timeFrame, 0.025)
flocks_cluster_filtered = flocks_cluster.drop(columns=['id', 'status', 'turn', 'speed', 'course', 'heading', 'lon', 'lat', 'ts', 'velocity'], axis=1) 

flocks_cluster_filtered = flocks_cluster_filtered.reset_index(drop=True)

flocks_cluster_filtered.crs = {'init': 'epsg:4326'}

tflst = []
for _, df in flocks_cluster_filtered.groupby('datetime'):
    
    tflst.append(df)

In [33]:
lst = instance.flock_label.value_counts().index.tolist()

In [11]:
def fix(df):
    cnt =1
    log = []
    for dt, instance in df.groupby('datetime'):
        if dt == flocks_cluster_filtered.datetime.min():
            log.append(instance)
            continue
#         log.append(instance.copy()) # 0
        order = instance.flock_label.value_counts().index.tolist()
#         log.append(order) # 1
        for label in order:
            if label == -1 or label not in log[-1].flock_label.unique(): continue
#             log.append(label) # 2,6,10,14...
            pair = (get_correct_label(instance.loc[instance.flock_label==label], log[-1]), label)
#             log.append(pair) # 3,7,11,15...
            instance['flock_label'] = instance.flock_label.apply(swap, args=(pair,))
#             log.append(instance) # 4,8,12,16...
            order = [swap(x,pair) for x in order]
#             log.append(order )# 5,9,13,17...
        log.append(instance) # -1
        print ('\r',cnt,'/',df.datetime.nunique())
        cnt+=1
    
    return pd.merge(log)

In [14]:
log = fix(flocks_cluster_filtered)

/home/theo/anaconda3/envs/gsa/lib/python3.6/site-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

 1 / 241
 2 / 241
 3 / 241
 4 / 241
 5 / 241
 6 / 241
 7 / 241
 8 / 241
 9 / 241
 10 / 241
 11 / 241
 12 / 241
 13 / 241
 14 / 241
 15 / 241
 16 / 241
 17 / 241
 18 / 241
 19 / 241
 20 / 241
 21 / 241
 22 / 241
 23 / 241
 24 / 241
 25 / 241
 26 / 241
 27 / 241
 28 / 241
 29 / 241
 30 / 241
 31 / 241
 32 / 241
 33 / 241
 34 / 241
 35 / 241
 36 / 241
 37 / 241
 38 / 241
 39 / 241
 40 / 241
 41 / 241
 42 / 241
 43 / 241
 44 / 241
 45 / 241
 46 / 241
 47 / 241
 48 / 241
 49 / 241
 50 / 241
 51 / 241
 52 / 241
 53 / 241
 54 / 241
 55 / 241
 56 / 241
 57 / 241
 58 / 241
 59 / 241
 60 / 241
 61 / 241

IndexError: index 1 is out of bounds for axis 0 with size 1

In [89]:
log[0]

,mmsi,geom,datetime,flock_label
71,227574020.0,POINT (-4.4966764 48.38252),2016-03-01 07:37:00,0
72,227006750.0,POINT (-4.484513300000001 48.381134),2016-03-01 07:37:00,0
73,227270000.0,POINT (-4.478275583333334 48.38315266666667),2016-03-01 07:37:00,0
74,227002330.0,POINT (-4.485928333333334 48.38144666666666),2016-03-01 07:37:00,0
75,304087000.0,POINT (-6.062419835294117 48.58990571764706),2016-03-01 07:37:00,-1
76,227578460.0,POINT (-4.466982 48.311195),2016-03-01 07:37:00,0
77,226263000.0,POINT (-4.485784833333334 48.379826),2016-03-01 07:37:00,0
78,227650230.0,POINT (-4.467682 48.317326),2016-03-01 07:37:00,0
79,227002630.0,POINT (-4.553500613333333 48.00590366666666),2016-03-01 07:37:00,-1
80,227408710.0,POINT (-4.4903984 48.379182),2016-03-01 07:37:00,0
81,227088590.0,POINT (-4.487552526666667 48.37803942222222),2016-03-01 07:37:00,0
82,226216000.0,POINT (-4.17526577 47.8357119),2016-03-01 07:37:00,-1
83,227322670.0,POINT (-4.4694934 48.319653),2016-03-01 07:37:00,0
84,228394000.0,POINT (-4.665965 48.1066),2016-03-01 07:37:00,1
85,227162950.0,POINT (-4.3274385 48.0992374),2016-03-01 07:37:00,2
86,227640710.0,POINT (-4.436395 48.325123),2016-03-01 07:37:00,0
87,227311000.0,POINT (-4.88224836 47.8787072),2016-03-01 07:37:00,-1
88,227315110.0,POINT (-4.4177 48.31473),2016-03-01 07:37:00,0
89,227654220.0,POINT (-4.44044 48.320225),2016-03-01 07:37:00,0
90,227612860.0,POINT (-4.495403288372093 48.38346235465117),2016-03-01 07:37:00,0
91,220417000.0,POINT (-4.484585 48.35214000000001),2016-03-01 07:37:00,0
92,227592820.0,POINT (-4.48885910989011 48.373142),2016-03-01 07:37:00,0
93,227148000.0,POINT (-4.498301166666667 48.38029833333333),2016-03-01 07:37:00,0
94,227686540.0,POINT (-4.4654617 48.32615999999999),2016-03-01 07:37:00,0
95,228236600.0,POINT (-4.378568593333333 47.816254),2016-03-01 07:37:00,-1
96,227589520.0,POINT (-4.479545 48.318474),2016-03-01 07:37:00,0
97,227705102.0,POINT (-4.4897285 48.371033),2016-03-01 07:37:00,0
98,227666970.0,POINT (-4.422177 48.316963),2016-03-01 07:37:00,0
99,227590030.0,POINT (-4.45394 48.3131),2016-03-01 07:37:00,0
100,256494000.0,POINT (-4.49788 48.355885),2016-03-01 07:37:00,0
...,...,...,...,...
112,228005700.0,POINT (-4.499144960629923 48.35229659055118),2016-03-01 07:37:00,0
113,227635210.0,POINT (-4.4970284 48.37953),2016-03-01 07:37:00,0
114,227142200.0,POINT (-4.327391599999999 48.099365),2016-03-01 07:37:00,2
115,227632830.0,POINT (-4.4566336 48.324116),2016-03-01 07:37:00,0
116,227303430.0,POINT (-4.4509835 48.32328),2016-03-01 07:37:00,0
117,412069000.0,POINT (-4.467607333333333 48.38087866666667),2016-03-01 07:37:00,0
118,477115900.0,POINT (-4.453365 48.38165),2016-03-01 07:37:00,0
119,227941000.0,POINT (-4.3272166 48.100094),2016-03-01 07:37:00,2
120,227016100.0,POINT (-4.48158 48.381454),2016-03-01 07:37:00,0
121,227003050.0,POINT (-4.5094786 48.36132),2016-03-01 07:37:00,0
122,228893000.0,POINT (-4.338938332542373 47.73893308135593),2016-03-01 07:37:00,-1
123,228762000.0,POINT (-4.528605000000001 48.352005),2016-03-01 07:37:00,0
124,227298110.0,POINT (-4.489409999999999 48.379013),2016-03-01 07:37:00,0
125,234056000.0,POINT (-4.7408967 48.297447),2016-03-01 07:37:00,-1
126,220364000.0,POINT (-6.21795399 48.05803333333333),2016-03-01 07:37:00,-1
127,227611930.0,POINT (-4.46831 48.315647),2016-03-01 07:37:00,0
128,228336000.0,POINT (-4.888929475 48.75238735),2016-03-01 07:37:00,-1
129,228849000.0,POINT (-4.827405864556962 48.23065963037975),2016-03-01 07:37:00,-1
130,228186700.0,POINT (-4.5124984 48.370834),2016-03-01 07:37:00,0
131,636015106.0,POINT (-4.473941666666667 48.33882266666666),2016-03-01 07:37:00,0
132,244630187.0,POINT (-4.488447133333334 48.37733166666667),2016-03-01 07:37:00,0
133,311043200.0,POINT (-3.572024958425197 49.69292394488189),2016-03-01 07:37:00,-1
134,227114630.0,POINT (-4.339089700000001 48.09767358333333),2016-03-01 07:37:00,2
135,227806500.0,POINT (-4.49574904 48.38124129999999),2016-03-01 07:37:00,0
136,228796000.0,POINT (-4.49543426 48.38203096),2016-03-01 07:37:00,0
137,249297000.0,POINT (-4.454394433333333 48.38516333333334),2016-03-01 07:37:00,0
138,227369960.0,POINT (-4.489070666666667 48.37796933333333),2016-03-01 07:37:00,0
139,227690560.0,POINT (-4.457615000000001 48.3413),2016-03-01 07:37:00,0
140,227588970.0,POINT (-4.448985 48.31286),2016-03-01 07:37:00,0
141,227322690.0,POINT (-4.4614415 48.340725),2016-03-01 07:37:00,0

In [94]:
log[14]

,mmsi,geom,datetime,flock_label
71,227574020.0,POINT (-4.4966764 48.38252),2016-03-01 07:37:00,0
72,227006750.0,POINT (-4.484513300000001 48.381134),2016-03-01 07:37:00,0
73,227270000.0,POINT (-4.478275583333334 48.38315266666667),2016-03-01 07:37:00,0
74,227002330.0,POINT (-4.485928333333334 48.38144666666666),2016-03-01 07:37:00,0
75,304087000.0,POINT (-6.062419835294117 48.58990571764706),2016-03-01 07:37:00,-1
76,227578460.0,POINT (-4.466982 48.311195),2016-03-01 07:37:00,0
77,226263000.0,POINT (-4.485784833333334 48.379826),2016-03-01 07:37:00,0
78,227650230.0,POINT (-4.467682 48.317326),2016-03-01 07:37:00,0
79,227002630.0,POINT (-4.553500613333333 48.00590366666666),2016-03-01 07:37:00,-1
80,227408710.0,POINT (-4.4903984 48.379182),2016-03-01 07:37:00,0
81,227088590.0,POINT (-4.487552526666667 48.37803942222222),2016-03-01 07:37:00,0
82,226216000.0,POINT (-4.17526577 47.8357119),2016-03-01 07:37:00,-1
83,227322670.0,POINT (-4.4694934 48.319653),2016-03-01 07:37:00,0
84,228394000.0,POINT (-4.665965 48.1066),2016-03-01 07:37:00,2
85,227162950.0,POINT (-4.3274385 48.0992374),2016-03-01 07:37:00,1
86,227640710.0,POINT (-4.436395 48.325123),2016-03-01 07:37:00,0
87,227311000.0,POINT (-4.88224836 47.8787072),2016-03-01 07:37:00,-1
88,227315110.0,POINT (-4.4177 48.31473),2016-03-01 07:37:00,0
89,227654220.0,POINT (-4.44044 48.320225),2016-03-01 07:37:00,0
90,227612860.0,POINT (-4.495403288372093 48.38346235465117),2016-03-01 07:37:00,0
91,220417000.0,POINT (-4.484585 48.35214000000001),2016-03-01 07:37:00,0
92,227592820.0,POINT (-4.48885910989011 48.373142),2016-03-01 07:37:00,0
93,227148000.0,POINT (-4.498301166666667 48.38029833333333),2016-03-01 07:37:00,0
94,227686540.0,POINT (-4.4654617 48.32615999999999),2016-03-01 07:37:00,0
95,228236600.0,POINT (-4.378568593333333 47.816254),2016-03-01 07:37:00,-1
96,227589520.0,POINT (-4.479545 48.318474),2016-03-01 07:37:00,0
97,227705102.0,POINT (-4.4897285 48.371033),2016-03-01 07:37:00,0
98,227666970.0,POINT (-4.422177 48.316963),2016-03-01 07:37:00,0
99,227590030.0,POINT (-4.45394 48.3131),2016-03-01 07:37:00,0
100,256494000.0,POINT (-4.49788 48.355885),2016-03-01 07:37:00,0
...,...,...,...,...
112,228005700.0,POINT (-4.499144960629923 48.35229659055118),2016-03-01 07:37:00,0
113,227635210.0,POINT (-4.4970284 48.37953),2016-03-01 07:37:00,0
114,227142200.0,POINT (-4.327391599999999 48.099365),2016-03-01 07:37:00,1
115,227632830.0,POINT (-4.4566336 48.324116),2016-03-01 07:37:00,0
116,227303430.0,POINT (-4.4509835 48.32328),2016-03-01 07:37:00,0
117,412069000.0,POINT (-4.467607333333333 48.38087866666667),2016-03-01 07:37:00,0
118,477115900.0,POINT (-4.453365 48.38165),2016-03-01 07:37:00,0
119,227941000.0,POINT (-4.3272166 48.100094),2016-03-01 07:37:00,1
120,227016100.0,POINT (-4.48158 48.381454),2016-03-01 07:37:00,0
121,227003050.0,POINT (-4.5094786 48.36132),2016-03-01 07:37:00,0
122,228893000.0,POINT (-4.338938332542373 47.73893308135593),2016-03-01 07:37:00,-1
123,228762000.0,POINT (-4.528605000000001 48.352005),2016-03-01 07:37:00,0
124,227298110.0,POINT (-4.489409999999999 48.379013),2016-03-01 07:37:00,0
125,234056000.0,POINT (-4.7408967 48.297447),2016-03-01 07:37:00,-1
126,220364000.0,POINT (-6.21795399 48.05803333333333),2016-03-01 07:37:00,-1
127,227611930.0,POINT (-4.46831 48.315647),2016-03-01 07:37:00,0
128,228336000.0,POINT (-4.888929475 48.75238735),2016-03-01 07:37:00,-1
129,228849000.0,POINT (-4.827405864556962 48.23065963037975),2016-03-01 07:37:00,-1
130,228186700.0,POINT (-4.5124984 48.370834),2016-03-01 07:37:00,0
131,636015106.0,POINT (-4.473941666666667 48.33882266666666),2016-03-01 07:37:00,0
132,244630187.0,POINT (-4.488447133333334 48.37733166666667),2016-03-01 07:37:00,0
133,311043200.0,POINT (-3.572024958425197 49.69292394488189),2016-03-01 07:37:00,-1
134,227114630.0,POINT (-4.339089700000001 48.09767358333333),2016-03-01 07:37:00,1
135,227806500.0,POINT (-4.49574904 48.38124129999999),2016-03-01 07:37:00,0
136,228796000.0,POINT (-4.49543426 48.38203096),2016-03-01 07:37:00,0
137,249297000.0,POINT (-4.454394433333333 48.38516333333334),2016-03-01 07:37:00,0
138,227369960.0,POINT (-4.489070666666667 48.37796933333333),2016-03-01 07:37:00,0
139,227690560.0,POINT (-4.457615000000001 48.3413),2016-03-01 07:37:00,0
140,227588970.0,POINT (-4.448985 48.31286),2016-03-01 07:37:00,0
141,227322690.0,POINT (-4.4614415 48.340725),2016-03-01 07:37:00,0

In [167]:
def fix2(df):
    lst = []
    grouped = df.groupby('datetime')
    for  ind, (ts, group) in enumerate(list(grouped)[:-1]):
        print (ind)
        for label, present in group.groupby('flock_label'):
            future = list(grouped)[ind+1][1]
            new_label = get_correct_label(present, future)
            lst.append(future)
            df.loc[df.datetime == future.iloc[0].datetime, 'flock_label'] = future['flock_label'].apply(swap, args=((new_label, label),))
            lst.append((new_label, label))
            lst.append(df.loc[df.datetime == future.iloc[0].datetime])
    return df, lst

In [172]:
for cnt, (ind, x) in enumerate(ndf.groupby('datetime')):
    if cnt >20: break
    gsplt.map_plot(x.loc[x.flock_label == 0])

HTTPError: Tile URL resulted in a 404 error. Double-check your tile url:
http://tile.stamen.com/terrain/19/255823/182031.png

In [50]:
grouped = flocks_cluster_filtered.groupby('datetime')

In [65]:
list(grouped)[0][1]

,mmsi,geom,datetime,flock_label
0,227408710.0,POINT (-4.4903984 48.3791865),2016-03-01 07:36:00,0
1,228853000.0,POINT (-3.891684385826772 47.73266998031496),2016-03-01 07:36:00,-1
2,227686540.0,POINT (-4.464395 48.32778),2016-03-01 07:36:00,0
3,226216000.0,POINT (-4.175265398333333 47.83571188333333),2016-03-01 07:36:00,-1
4,227270000.0,POINT (-4.478274466666667 48.38315333333333),2016-03-01 07:36:00,0
5,249297000.0,POINT (-4.454358866666666 48.38522166666666),2016-03-01 07:36:00,0
6,227142200.0,POINT (-4.327391599999999 48.09936),2016-03-01 07:36:00,1
7,227222000.0,POINT (-4.477003 48.38212),2016-03-01 07:36:00,0
8,227300000.0,POINT (-4.6446233 48.10234000000001),2016-03-01 07:36:00,2
9,227632830.0,POINT (-4.4594316 48.32465999999999),2016-03-01 07:36:00,0
10,227639660.0,POINT (-4.4669685 48.31886),2016-03-01 07:36:00,0
11,220364000.0,POINT (-6.221534542500001 48.05431666666666),2016-03-01 07:36:00,-1
12,228236700.0,POINT (-4.5354633 48.12284),2016-03-01 07:36:00,-1
13,227008170.0,POINT (-4.486165 48.3815),2016-03-01 07:36:00,0
14,228336000.0,POINT (-4.88961595 48.75200870000001),2016-03-01 07:36:00,-1
15,227806500.0,POINT (-4.495805030000001 48.381350975),2016-03-01 07:36:00,0
16,227002330.0,POINT (-4.485915 48.38144),2016-03-01 07:36:00,0
17,227590030.0,POINT (-4.4543715 48.31307),2016-03-01 07:36:00,0
18,227003050.0,POINT (-4.503830000000001 48.36275999999999),2016-03-01 07:36:00,0
19,228236600.0,POINT (-4.378567186666666 47.816254),2016-03-01 07:36:00,-1
20,227589520.0,POINT (-4.48326 48.3186),2016-03-01 07:36:00,0
21,227002630.0,POINT (-4.55352006 48.00590275),2016-03-01 07:36:00,-1
22,227635210.0,POINT (-4.497023 48.379536),2016-03-01 07:36:00,0
23,227612860.0,POINT (-4.495403170930231 48.3834624491279),2016-03-01 07:36:00,0
24,226263000.0,POINT (-4.4857864 48.379826),2016-03-01 07:36:00,0
25,228005700.0,POINT (-4.499382637795277 48.35242743307087),2016-03-01 07:36:00,0
26,227369960.0,POINT (-4.489066749999999 48.377969),2016-03-01 07:36:00,0
27,227705102.0,POINT (-4.4922233 48.374924),2016-03-01 07:36:00,0
28,227941000.0,POINT (-4.327215 48.100086),2016-03-01 07:36:00,1
29,227592820.0,POINT (-4.488851069230769 48.3731392),2016-03-01 07:36:00,0
...,...,...,...,...
41,227016100.0,POINT (-4.4816 48.38144),2016-03-01 07:36:00,0
42,227690560.0,POINT (-4.456775 48.343277),2016-03-01 07:36:00,0
43,234056000.0,POINT (-4.7373915 48.298428),2016-03-01 07:36:00,-1
44,228796000.0,POINT (-4.49543532 48.38203172),2016-03-01 07:36:00,0
45,227006750.0,POINT (-4.484496599999999 48.381153),2016-03-01 07:36:00,0
46,227322670.0,POINT (-4.469571599999999 48.321705),2016-03-01 07:36:00,0
47,227148000.0,POINT (-4.498298933333333 48.38029666666666),2016-03-01 07:36:00,0
48,228893000.0,POINT (-4.338887259152543 47.73891577288136),2016-03-01 07:36:00,-1
49,477115900.0,POINT (-4.4533705 48.381656),2016-03-01 07:36:00,0
50,227574020.0,POINT (-4.496205000000001 48.382614),2016-03-01 07:36:00,0
51,220417000.0,POINT (-4.484576000000001 48.35213),2016-03-01 07:36:00,0
52,227588970.0,POINT (-4.451975 48.3136),2016-03-01 07:36:00,0
53,227650230.0,POINT (-4.467698 48.318214),2016-03-01 07:36:00,0
54,228762000.0,POINT (-4.523613500000001 48.35285),2016-03-01 07:36:00,0
55,227114630.0,POINT (-4.3390894 48.097673),2016-03-01 07:36:00,1
56,636015106.0,POINT (-4.473920033333334 48.33880133333334),2016-03-01 07:36:00,0
57,227654220.0,POINT (-4.4432964 48.321106),2016-03-01 07:36:00,0
58,227640710.0,POINT (-4.433726999999999 48.3259),2016-03-01 07:36:00,0
59,227311000.0,POINT (-4.88226502 47.8790804),2016-03-01 07:36:00,-1
60,228394000.0,POINT (-4.665362 48.106667),2016-03-01 07:36:00,2
61,244630187.0,POINT (-4.488446916666667 48.37733083333333),2016-03-01 07:36:00,0
62,412069000.0,POINT (-4.467614666666667 48.38088233333333),2016-03-01 07:36:00,0
63,227730220.0,POINT (-4.49239 48.35788),2016-03-01 07:36:00,0
64,227088590.0,POINT (-4.487552053333333 48.37803884444444),2016-03-01 07:36:00,0
65,227631450.0,POINT (-4.471657 48.31042),2016-03-01 07:36:00,0
66,227315110.0,POINT (-4.419327 48.31531),2016-03-01 07:36:00,0
67,228849000.0,POINT (-4.827430906329114 48.23077410886076),2016-03-01 07:36:00,-1
68,227578460.0,POINT (-4.466825 48.31256),2016-03-01 07:36:00,0
69,227162950.0,POINT (-4.327438666666667 48.09923746666666),2016-03-01 07:36:00,1
70,228186700.0,POINT (-4.512576599999999 48.370853),2016-03-01 07:36:00,0

In [82]:
def get_list(df):
    lst = []
    for ts, sdf in df.groupby('datetime'):
        lst.append((ts, sdf.flock_label.unique().tolist()))

In [83]:
def join(df, lst):
    for ts, labels in lst:
        group = df.groupby('datetime').get_group(ts)

SyntaxError: unexpected EOF while parsing (<ipython-input-83-27d955b7486a>, line 1)

In [81]:
type(flocks_cluster_filtered.flock_label.unique().tolist())

list

In [84]:
test = flocks_cluster_filtered[:20].copy()

In [128]:
test.groupby(['datetime'])['flock_label'].get_group('2016-03-01 07:36:00')

0     1
1     0
2     1
3     0
4     1
5     1
6     2
7     1
8     3
9     1
10    1
11    0
12    0
13    1
14    0
15    1
16    1
17    1
18    1
19    0
Name: flock_label, dtype: int64

In [108]:
test

,mmsi,geom,datetime,flock_label,flock_label1
0,227408710.0,POINT (-4.4903984 48.3791865),2016-03-01 07:36:00,1,1
1,228853000.0,POINT (-3.891684385826772 47.73266998031496),2016-03-01 07:36:00,0,0
2,227686540.0,POINT (-4.464395 48.32778),2016-03-01 07:36:00,1,1
3,226216000.0,POINT (-4.175265398333333 47.83571188333333),2016-03-01 07:36:00,0,0
4,227270000.0,POINT (-4.478274466666667 48.38315333333333),2016-03-01 07:36:00,1,1
5,249297000.0,POINT (-4.454358866666666 48.38522166666666),2016-03-01 07:36:00,1,1
6,227142200.0,POINT (-4.327391599999999 48.09936),2016-03-01 07:36:00,2,2
7,227222000.0,POINT (-4.477003 48.38212),2016-03-01 07:36:00,1,1
8,227300000.0,POINT (-4.6446233 48.10234000000001),2016-03-01 07:36:00,3,3
9,227632830.0,POINT (-4.4594316 48.32465999999999),2016-03-01 07:36:00,1,1
10,227639660.0,POINT (-4.4669685 48.31886),2016-03-01 07:36:00,1,1
11,220364000.0,POINT (-6.221534542500001 48.05431666666666),2016-03-01 07:36:00,0,0
12,228236700.0,POINT (-4.5354633 48.12284),2016-03-01 07:36:00,0,0
13,227008170.0,POINT (-4.486165 48.3815),2016-03-01 07:36:00,1,1
14,228336000.0,POINT (-4.88961595 48.75200870000001),2016-03-01 07:36:00,0,0
15,227806500.0,POINT (-4.495805030000001 48.381350975),2016-03-01 07:36:00,1,1
16,227002330.0,POINT (-4.485915 48.38144),2016-03-01 07:36:00,1,1
17,227590030.0,POINT (-4.4543715 48.31307),2016-03-01 07:36:00,1,1
18,227003050.0,POINT (-4.503830000000001 48.36275999999999),2016-03-01 07:36:00,1,1
19,228236600.0,POINT (-4.378567186666666 47.816254),2016-03-01 07:36:00,0,0